# ESTIMATIVA POR MÍNIMO QUADRADO

In [45]:
import numpy as np
import pandas as pd
import scipy as sp

In [46]:
# IMPORTAÇÃO DO DATAFRAME
# Substitua 'ID_DO_ARQUIVO' pelo ID real que você copiou do link
file_id = '1w0MhxeKDMbsR_HXVLzxTh8YZZzyWVsw-'
url = f'https://drive.google.com/uc?id={file_id}'           
# O pandas agora consegue acessar o arquivo puramente
nota = pd.read_excel(url)

In [47]:
nota.head(25)

    inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [48]:
nota.shape

(25, 3)

In [49]:
# como que o python reconhecer os tipos de dados
nota.dtypes

inicio_estudo         int64
tempo_estudo_dia      int64
nota                float64
dtype: object

In [50]:
# Valores Missing (NAN)
nota.isnull().sum()

inicio_estudo       0
tempo_estudo_dia    0
nota                0
dtype: int64

In [51]:
A = nota.drop(columns=['nota'])
A.head()

   inicio_estudo  tempo_estudo_dia
0              5               120
1             13                90
2             20               120
3             28                60
4             20               150

In [52]:
type(A)

pandas.core.frame.DataFrame

In [53]:
A = A.values
print(A)

[[  5 120]
 [ 13  90]
 [ 20 120]
 [ 28  60]
 [ 20 150]
 [ 24 150]
 [ 18  60]
 [  8 120]
 [  2 240]
 [ 12  90]
 [ 15  90]
 [  9 120]
 [  6 180]
 [  4  90]
 [  8 150]
 [ 12 120]
 [ 10 180]
 [  3  90]
 [ 15 180]
 [  9  90]
 [ 24 120]
 [  5 150]
 [  7 120]
 [ 12 180]
 [  2  90]]

In [54]:
type(A)

numpy.ndarray

In [55]:
b = nota.drop(columns=['inicio_estudo','tempo_estudo_dia'])
b.head()

   nota
0   8.1
1   6.8
2   7.0
3   7.4
4   9.3

In [56]:
b = b.values
b

array([[8.1],
       [6.8],
       [7. ],
       [7.4],
       [9.3],
       [7.5],
       [7.6],
       [8. ],
       [7. ],
       [7.3],
       [8.6],
       [8.3],
       [7.9],
       [6.4],
       [7.8],
       [9.4],
       [8.8],
       [6.9],
       [7.7],
       [8.2],
       [8.6],
       [8.1],
       [7.2],
       [8.5],
       [6.1]])

Estimativa por mínimos quadrados \
$\vec{x} = (A^TA)^{-1}A^Tb$

In [57]:
# Transposta da Matriz A
At = np.array(A).T
At

array([[  5,  13,  20,  28,  20,  24,  18,   8,   2,  12,  15,   9,   6,
          4,   8,  12,  10,   3,  15,   9,  24,   5,   7,  12,   2],
       [120,  90, 120,  60, 150, 150,  60, 120, 240,  90,  90, 120, 180,
         90, 150, 120, 180,  90, 180,  90, 120, 150, 120, 180,  90]])

In [58]:
print(A)

[[  5 120]
 [ 13  90]
 [ 20 120]
 [ 28  60]
 [ 20 150]
 [ 24 150]
 [ 18  60]
 [  8 120]
 [  2 240]
 [ 12  90]
 [ 15  90]
 [  9 120]
 [  6 180]
 [  4  90]
 [  8 150]
 [ 12 120]
 [ 10 180]
 [  3  90]
 [ 15 180]
 [  9  90]
 [ 24 120]
 [  5 150]
 [  7 120]
 [ 12 180]
 [  2  90]]

In [59]:
AtA = np.dot(At,A)
AtA

array([[  4669,  34950],
       [ 34950, 441900]])

In [60]:
AtAinv = np.linalg.inv(AtA)
AtAinv

array([[ 5.24991072e-04, -4.15216971e-05],
       [-4.15216971e-05,  5.54691857e-06]])

In [63]:
Atb = np.dot(At, b)
Atb

array([[ 2305.9],
       [24726. ]])

In [65]:
x = np.dot(AtAinv,Atb)
x

array([[0.18391143],
       [0.04140823]])

In [66]:
x = np.dot(np.dot(np.linalg.inv(np.dot(At,A)),At),b)
print(x)

[[0.18391143]
 [0.04140823]]

nota = 0,1839.inicio_estudo + 0,0414.tempo_estudo_dia

In [67]:
resultado = nota
resultado

    inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [69]:
resultado['previsao'] = resultado['inicio_estudo']*x[0] + resultado['tempo_estudo_dia']*x[1]
resultado

    inicio_estudo  tempo_estudo_dia  nota   previsao
0               5               120   8.1   5.888544
1              13                90   6.8   6.117589
2              20               120   7.0   8.647216
3              28                60   7.4   7.634014
4              20               150   9.3   9.889463
5              24               150   7.5  10.625108
6              18                60   7.6   5.794899
7               8               120   8.0   6.440279
8               2               240   7.0  10.305797
9              12                90   7.3   5.933678
10             15                90   8.6   6.485412
11              9               120   8.3   6.624190
12              6               180   7.9   8.556949
13              4                90   6.4   4.462386
14              8               150   7.8   7.682525
15             12               120   9.4   7.175924
16             10               180   8.8   9.292595
17              3                90   6.9   4.278475
18             15               180   7.7  10.212152
19              9                90   8.2   5.381943
20             24               120   8.6   9.382862
21              5               150   8.1   7.130791
22              7               120   7.2   6.256367
23             12               180   8.5   9.660418
24              2                90   6.1   4.094563

In [71]:
# Erro Médio Absoluto (MAE)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(resultado.nota, resultado.previsao)

1.5823602999826785

In [77]:
resultado['erro_abs'] = abs(resultado.nota - resultado.previsao)
resultado

    inicio_estudo  tempo_estudo_dia  nota   previsao  erro_abs
0               5               120   8.1   5.888544  2.211456
1              13                90   6.8   6.117589  0.682411
2              20               120   7.0   8.647216  1.647216
3              28                60   7.4   7.634014  0.234014
4              20               150   9.3   9.889463  0.589463
5              24               150   7.5  10.625108  3.125108
6              18                60   7.6   5.794899  1.805101
7               8               120   8.0   6.440279  1.559721
8               2               240   7.0  10.305797  3.305797
9              12                90   7.3   5.933678  1.366322
10             15                90   8.6   6.485412  2.114588
11              9               120   8.3   6.624190  1.675810
12              6               180   7.9   8.556949  0.656949
13              4                90   6.4   4.462386  1.937614
14              8               150   7.8   7.682525  0.117475
15             12               120   9.4   7.175924  2.224076
16             10               180   8.8   9.292595  0.492595
17              3                90   6.9   4.278475  2.621525
18             15               180   7.7  10.212152  2.512152
19              9                90   8.2   5.381943  2.818057
20             24               120   8.6   9.382862  0.782862
21              5               150   8.1   7.130791  0.969209
22              7               120   7.2   6.256367  0.943633
23             12               180   8.5   9.660418  1.160418
24              2                90   6.1   4.094563  2.005437

Erro Médio Absoluto (MAE - Mean Absolute Error) \
MAE = $(1/n)\sum_{i=1}^{n} (y_i - \hat{y})$

In [87]:
somatorio = (sum(resultado.erro_abs))/25
somatorio

1.5823602999826785

In [ ]:
def produto_interno_vetores(vetor1:np.array,vetor2:np.array) -> float:
    while len(vetor1)<len(vetor2):
        vetor1 = np.append(vetor1,0)
    while len(vetor1)>len(vetor2):
        vetor2 = np.append(vetor2,0)
    return float(np.dot(vetor1, vetor2))

In [138]:
v1 = [1,2,3,4]
v2 = [1,2,3]
# Calculamos o tamanho do menor deles usando a função min()
min_len = min(len(v1), len(v2)) 
print(f'O mínimo entre os dois vetores é: {min_len}')
# Aqui, min_len será igual a 3
v_res = np.dot(v1[:min_len], v2[:min_len])
print(f"O produto é: {v_res}")

# Por que isso é eficiente?
# Você não precisou criar um loop while nem adicionar zeros. 
# O "corte" [:min_len] é uma operação extremamente rápida no NumPy, 
# pois ele não copia os dados, apenas cria uma "visão" reduzida do vetor original.

O mínimo entre os dois vetores é: 3
O produto é: 14