Criação de um modelo de regressão linear múltipla \
\
$y = b_0 + b_1x_1 + b_2x_2 + ... + b_nx_n + E$

In [2]:
import numpy as np
import pandas as pd
import scipy as sp

In [4]:
# IMPORTAÇÃO DO DATAFRAME
# Substitua 'ID_DO_ARQUIVO' pelo ID real que você copiou do link
file_id = '1w0MhxeKDMbsR_HXVLzxTh8YZZzyWVsw-'
url = f'https://drive.google.com/uc?id={file_id}'           
# O pandas agora consegue acessar o arquivo puramente
nota = pd.read_excel(url)  
resultado = nota

In [5]:
resultado.head()

   inicio_estudo  tempo_estudo_dia  nota
0              5               120   8.1
1             13                90   6.8
2             20               120   7.0
3             28                60   7.4
4             20               150   9.3

In [7]:
A = resultado.drop(columns=['nota'])
A.head()

   inicio_estudo  tempo_estudo_dia
0              5               120
1             13                90
2             20               120
3             28                60
4             20               150

In [9]:
A = A.assign(unidade=1)
A.head()

   inicio_estudo  tempo_estudo_dia  unidade
0              5               120        1
1             13                90        1
2             20               120        1
3             28                60        1
4             20               150        1

In [11]:
A = A[['unidade', 'inicio_estudo', 'tempo_estudo_dia']]
A.head()

   unidade  inicio_estudo  tempo_estudo_dia
0        1              5               120
1        1             13                90
2        1             20               120
3        1             28                60
4        1             20               150

In [18]:
b = resultado.drop(columns=['inicio_estudo', 'tempo_estudo_dia'])
b = b.values
b

array([[8.1],
       [6.8],
       [7. ],
       [7.4],
       [9.3],
       [7.5],
       [7.6],
       [8. ],
       [7. ],
       [7.3],
       [8.6],
       [8.3],
       [7.9],
       [6.4],
       [7.8],
       [9.4],
       [8.8],
       [6.9],
       [7.7],
       [8.2],
       [8.6],
       [8.1],
       [7.2],
       [8.5],
       [6.1]])

In [19]:
At = np.array(A.T)
At

array([[  1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,
          1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1],
       [  5,  13,  20,  28,  20,  24,  18,   8,   2,  12,  15,   9,   6,
          4,   8,  12,  10,   3,  15,   9,  24,   5,   7,  12,   2],
       [120,  90, 120,  60, 150, 150,  60, 120, 240,  90,  90, 120, 180,
         90, 150, 120, 180,  90, 180,  90, 120, 150, 120, 180,  90]])

In [21]:
x = np.dot(np.dot(np.linalg.inv(np.dot(At,A)),At),b)
x

array([[6.48712882e+00],
       [4.13304622e-02],
       [6.44273496e-03]])

nota = 6,4871 + 0,0413.inicio_estudo + 0,00644.tempo_estudo_dia

In [22]:
resultado['previsao'] = x[0] + resultado['inicio_estudo']*x[1] + resultado['tempo_estudo_dia']*x[2]
resultado

    inicio_estudo  tempo_estudo_dia  nota  previsao
0               5               120   8.1  7.466909
1              13                90   6.8  7.604271
2              20               120   7.0  8.086866
3              28                60   7.4  8.030946
4              20               150   9.3  8.280148
5              24               150   7.5  8.445470
6              18                60   7.6  7.617641
7               8               120   8.0  7.590901
8               2               240   7.0  8.116046
9              12                90   7.3  7.562941
10             15                90   8.6  7.686932
11              9               120   8.3  7.632231
12              6               180   7.9  7.894804
13              4                90   6.4  7.232297
14              8               150   7.8  7.784183
15             12               120   9.4  7.756223
16             10               180   8.8  8.060126
17              3                90   6.9  7.190966
18             15               180   7.7  8.266778
19              9                90   8.2  7.438949
20             24               120   8.6  8.252188
21              5               150   8.1  7.660191
22              7               120   7.2  7.549570
23             12               180   8.5  8.142787
24              2                90   6.1  7.149636

In [23]:
# Erro Médio Absoluto (MAE)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(resultado.nota, resultado.previsao)

0.6362742744691536

In [24]:
resultado['erro_abs'] = abs(resultado.nota - resultado.previsao)
resultado

    inicio_estudo  tempo_estudo_dia  nota  previsao  erro_abs
0               5               120   8.1  7.466909  0.633091
1              13                90   6.8  7.604271  0.804271
2              20               120   7.0  8.086866  1.086866
3              28                60   7.4  8.030946  0.630946
4              20               150   9.3  8.280148  1.019852
5              24               150   7.5  8.445470  0.945470
6              18                60   7.6  7.617641  0.017641
7               8               120   8.0  7.590901  0.409099
8               2               240   7.0  8.116046  1.116046
9              12                90   7.3  7.562941  0.262941
10             15                90   8.6  7.686932  0.913068
11              9               120   8.3  7.632231  0.667769
12              6               180   7.9  7.894804  0.005196
13              4                90   6.4  7.232297  0.832297
14              8               150   7.8  7.784183  0.015817
15             12               120   9.4  7.756223  1.643777
16             10               180   8.8  8.060126  0.739874
17              3                90   6.9  7.190966  0.290966
18             15               180   7.7  8.266778  0.566778
19              9                90   8.2  7.438949  0.761051
20             24               120   8.6  8.252188  0.347812
21              5               150   8.1  7.660191  0.439809
22              7               120   7.2  7.549570  0.349570
23             12               180   8.5  8.142787  0.357213
24              2                90   6.1  7.149636  1.049636

In [26]:
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [30]:
# Criação do modelo usando a biblioteca Statsmodels
modelo = smf.ols('nota ~ inicio_estudo + tempo_estudo_dia', data = nota).fit()

In [31]:
print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   nota   R-squared:                       0.184
Model:                            OLS   Adj. R-squared:                  0.110
Method:                 Least Squares   F-statistic:                     2.485
Date:                Mon, 02 Feb 2026   Prob (F-statistic):              0.106
Time:                        02:03:34   Log-Likelihood:                -28.151
No. Observations:                  25   AIC:                             62.30
Df Residuals:                      22   BIC:                             65.96
Df Model:                           2
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            6.4871      0.624     10.400      0.000       5.193       7.781
inicio_estudo        0.0413      0.023      1.812      0.084      -0.006       0.089
tempo_estudo_dia     0.0064      0.004      1.674      0.108      -0.002       0.014
==============================================================================
Omnibus:                        1.269   Durbin-Watson:                   1.868
Prob(Omnibus):                  0.530   Jarque-Bera (JB):                0.933
Skew:                           0.155   Prob(JB):                        0.627
Kurtosis:                       2.106   Cond. No.                         523.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.